name       : python3-cairo
version    : 1.14.1
release    : 8
source     :
    - https://github.com/pygobject/pycairo/releases/download/v1.14.1/pycairo-1.14.1.tar.gz : 0d13a0a6eeaf0c357db04392943eb9b25767445608d31dde1307f003f68c5754
license    : GPL-2.0
component  : programming.python
summary    : Python3 Cairo Bindings
description: |
    Python3 Cairo Bindings
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(cairo)
build      : |
    %python3_setup
install    : |
    %python3_install
