name       : python3-cairo
version    : 1.18.0
release    : 9
source     :
    - https://github.com/pygobject/pycairo/releases/download/v1.18.0/pycairo-1.18.0.tar.gz : abd42a4c9c2069febb4c38fe74bfc4b4a9d3a89fea3bc2e4ba7baff7a20f783f
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python3 Cairo Bindings
description: |
    Python3 Cairo Bindings
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(cairo)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
