name       : python3-cairo
version    : 1.10.0
release    : 4
source     :
    - http://cairographics.org/releases/pycairo-1.10.0.tar.bz2 : 9aa4078e7eb5be583aeabbe8d87172797717f95e8c4338f0d4a17b683a7253be
license    : GPL-2.0 
summary    : Python3 Cairo Bindings
description: |
    Python3 Cairo Bindings
builddeps  :
    - pkgconfig(python-3.4)
    - pkgconfig(cairo)
setup      : |
    %patch -p1 < $pkgfiles/pycairo-1.10.0-waf-python3.4.patch
    export PYTHON=/usr/bin/python3
    ./waf configure --prefix=/usr --bindir=/usr/bin --libdir=%libdir% -j5
build  : |
    ./waf build
install : |
    ./waf install --destdir="$installdir"
    ./waf clean
