name       : python3-cairo
version    : 1.20.0
release    : 14
source     :
    - https://github.com/pygobject/pycairo/releases/download/v1.20.0/pycairo-1.20.0.tar.gz : 5695a10cb7f9ae0d01f665b56602a845b0a8cb17e2123bfece10c2e58552468c
license    : LGPL-2.1-or-later
component  : programming.python
summary    : Python3 Cairo Bindings
description: |
    Python3 Cairo Bindings
builddeps  :
    - pkgconfig(python3)
    - pkgconfig(cairo)
    - python-pytest
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test
